### ISSUE TITLE
[FEATURE REQUEST] Config Effect Level

### ISSUE THREAD

**Issue by TomtomFH** [CERBON-MODS/CERBONs-Better-Beacons#10]
## Before submitting the feature request

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of Better Beacons mod**
- [x] **I have checked the [FAQ](https://github.com/CERBON-MODS/CERBONs-Better-Beacons/blob/master/FAQ.md) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/CERBON-MODS/CERBONs-Better-Beacons/blob/master/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/CERBON-MODS/CERBONs-Better-Beacons/blob/master/CODE_OF_CONDUCT.md)**

## Is your feature request related to a problem? Please describe.
I Just grinded for one layer of netherite for my beacon and i was a bit underwhelmed by the level of the effect being only IV and not V since i would like to have a clean number like V as my level for a maxed beacon.

## Describe the solution/feature you'd like
I would like to see the level of the effect being customizable in the config for specific blocks. (maybe also the blocks that you can use for the beacon)

## Describe alternatives you've considered
maybe customizable by commands?

## Additional context
![image](https://github.com/CERBON-MODS/CERBONs-Better-Beacons/assets/103309136/9b26797a-5f09-492e-be53-a584f34d99c9)

**Comment by CerbonXD** [comment]
You can configure the beacon primary effects strength by using a datapack. See: https://github.com/CERBON-MODS/CERBONs-Better-Beacons/wiki/Datapack

**Comment by TomtomFH** [comment]
I am aware of this posibility but most people dont know how to use or modify datapacks. easily changing configs ingame can be done using a different mod but i havnt found one that can modify datapacks ingame yet. What im trying to say is: it would be a lot easier to understand and configurate the mod for users that dont know that much about modding to have the option to modify the above features in the config files.

**Comment by CerbonXD** [comment]
Agree with you that config fies are easier for people that has less knowledge about the game, however, datapacks are still a better option in my opinion for people who wants to modify the mod. Everything would be in the same place instead of part of the config for some blocks being in one place and to add more blocks you would need to use a datapack in another place.

**Comment by TomtomFH** [comment]
well you could make the user able to add blocks and their levels in the config for example:
["Blocks"]
  "Block1" = 1
  "Block2" = 2
  "Block3" = 3
This would also make everything be in one place and make the modifying of each blocks effect strength easier for less knowledgeable people to change the beacon to their liking.

**Comment by CerbonXD** [comment]
I can't make it in the config file. Cloth config does not support the use of HashMaps.
